[project]
name = "taxi-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "prefect>=3.4.1",
    "pyarrow>=20.0.0",
    "requests>=2.32.3",
]
